package com.example.eworkout.authentication.signup.model

enum class SignupState{
    ERROR_FIRST_NAME_EMPTY,
    ERROR_FIRST_NAME_LENGTH,
    ERROR_LAST_NAME_EMPTY,
    ERROR_LAST_NAME_LENGTH,
    ERROR_EMAIL_EMPTY,
    ERROR_EMAIL_FORMAT,
    ERROR_USED_EMAIL,
    ERROR_PASSWORD_EMPTY,
    ERROR_PASSWORD_LENGTH,
    ERROR_CONFIRM_PASSWORD_MATCH,
    NO_ERROR_FIRST_NAME,
    NO_ERROR_LAST_NAME,
    NO_ERROR_EMAIL,
    NO_ERROR_PASSWORD,
    NO_ERROR_CONFIRM_PASSWORD,
    SUCCESS,
    GOOGLE_SIGN_IN_SUCCESS,
    LOADING

}